#!/usr/bin/with-contenv bash

set -e

echo ""
echo "***** Set profile *****"
echo ""
[[ ! -e "/etc/profile.d/ff-profile.sh" ]] && {
    ln -s ${FF_DATA}/ff-profile.sh /etc/profile.d/ff-profile.sh
}
source /etc/profile.d/ff-profile.sh

FF_RESTART_COUNT=0
printf "${FF_RESTART_COUNT}" > /var/run/s6/container_environment/FF_RESTART_COUNT

echo ""
echo "***** Install the required packages *****"
echo ""
[ ${FF_REQUIREMENTS_APT_INSTALL:-true} == true ] && apt-get update && apt-get install -y ${FF_REQUIREMENTS_APT_LIST}

echo ""
echo "***** Clone flaskfarm *****"
echo ""
# flaskfarm 소스 설치
if [[ -e "${FF_SRC}/.git" ]]; then
    # config.yaml의 debug 옵션이 true 가 아니면 pull 로 소스 업데이트
    if [[ ! ${FF_DEBUG:-false} == true ]]; then
        git config --global --add safe.directory ${FF_SRC}
        git -C ${FF_SRC} pull "${FF_REPO}"
    fi
else
    git clone "${FF_REPO}" "${FF_SRC}"
fi

echo ""
echo "***** Install the flaskfarm package in 'edit' mode *****"
echo ""
pip install -U pip setuptools && pip install -e "${FF_ROOT}"

echo ""
echo "***** Change the folder permissions *****"
echo ""
[[ -d "${FF_DATA}" ]] && chown abc:abc -R "${FF_DATA}"
[[ -d "${FF_SRC}" ]] && chown abc:abc -R "${FF_SRC}"
mkdir -p "${FF_PATH_DEV}"
[[ -d "${FF_PATH_DEV}" ]] && chown abc:abc -R "${FF_PATH_DEV}"

echo ""
echo "***** Cleanup *****"
echo ""
apt-get clean && \
python3 -m pip cache purge && \
rm -rf \
    /tmp/* \
    /var/lib/apt/lists/* \
    /var/tmp/*
