#!/usr/bin/with-contenv bash

set -e

echo ""
echo "***** Set profile *****"
echo ""

[[ ! -e "/etc/profile.d/ff-profile.sh" ]] && {
    ln -s ${FF_DATA}/ff-profile.sh /etc/profile.d/ff-profile.sh
}
source /etc/profile.d/ff-profile.sh

FF_RESTART_COUNT=0
printf "${FF_RESTART_COUNT}" > /var/run/s6/container_environment/FF_RESTART_COUNT

echo ""
echo "***** Install user-defined extra APT packages *****"
echo ""
[ ${FF_USER_APT_INSTALL:-false} == true ] && apt-get update && apt-get install -y ${FF_USER_APT_LIST}

echo ""
echo "***** Setup SSH Password *****"
echo ""
# root 계정 비밀번호 설정
PASS="${SSH_PASSWORD:-flaskfarm}"
echo "root:${PASS}" | chpasswd

echo ""
echo "***** Clone flaskfarm *****"
echo ""
# flaskfarm 소스 설치
mkdir -p "${FF_SRC}"
chown abc:abc "${FF_SRC}"
if [[ -e "${FF_SRC}/flaskfarm/.git" ]]; then
    # config.yaml의 debug 옵션이 true 가 아니면 pull 로 소스 업데이트
    if [[ ! ${FF_DEBUG:-true} == true ]]; then
        git config --global --add safe.directory ${FF_SRC}/flaskfarm
        git -C "${FF_SRC}/flaskfarm" pull "${FF_REPO}"
    fi
else
    git clone "${FF_REPO}" "${FF_SRC}/flaskfarm"
    chown abc:abc "${FF_SRC}/flaskfarm"
fi

echo ""
echo "***** Install the flaskfarm package in 'edit' mode *****"
echo ""
pip install --no-deps -e "${FF_ROOT}"

echo ""
echo "***** Cleanup *****"
echo ""
apt-get clean && \
python3 -m pip cache purge && \
rm -rf \
    /tmp/* \
    /var/lib/apt/lists/* \
    /var/tmp/*
